pipeline {
    agent any

    stages {

        stage('Build') {
            steps {
                echo 'Building Saving Service...'
                sh './mvnw clean package -DskipTests'
            }
        }

    }
}
